-- buat database
-- CREATE DATABASE BUKOPIN2;

-- buat tabel
-- CREATE TABLE PEGAWAI(
-- 	ID_PEGAWAI INTEGER PRIMARY KEY,
-- 	UMUR INTEGER,
-- 	NAMA_PEGAWAI TEXT
-- );

-- rename tabel
-- ALTER TABLE PEGAWAI RENAME TO PEGAWAI2

-- CREATE TABLE FILM(
-- 	KD_FILM TEXT PRIMARY KEY,
-- 	NM_FILM TEXT,
-- 	GENRE TEXT,
-- 	ARTIS TEXT,
-- 	PRODUSER TEXT,
-- 	PENDAPATAN INTEGER,
-- 	NOMINASI INTEGER
-- );

-- SELECT * FROM FILM;

-- INSERT INTO PEGAWAI2(ID_PEGAWAI, UMUR, NAMA_PEGAWAI)VALUES(1,23,'ARNOLD S');
-- INSERT INTO PEGAWAI2 VALUES(2,23,'RAMBO S');
-- INSERT INTO PEGAWAI2(ID_PEGAWAI)VALUES(3);
-- INSERT INTO PEGAWAI2(UMUR)VALUES(24); << ERROR KARENA ID PEGAWAI ADALAH PRIMARY KEY
-- INSERT INTO PEGAWAI2
-- VALUES
-- (4,22,'WHISNU'),
-- (5,25,'ARMADA'),
-- (6,25,'JHON D');

-- SELECT * FROM PEGAWAI2;

-- UPDATE PEGAWAI2 SET 
-- UMUR = 21, NAMA_PEGAWAI = 'SHISUKA'
-- WHERE ID_PEGAWAI = 3;
-- disaat ada perubahan, urutan akan pindah kepaling bawah (postgree)

-- DELETE FROM PEGAWAI2 WHERE ID_PEGAWAI = 3;

-- SELECT 'XSIS'
-- SELECT 100
-- SELECT 100*3 AS "HASIL KALI"
-- SELECT NAMA_PEGAWAI, UMUR*3 AS "HASIL KALI" FROM PEGAWAI2
-- SELECT * FROM PEGAWAI2 ORDER BY UMUR DESC
-- SELECT DISTINCT(UMUR) FROM PEGAWAI2
-- SELECT * FROM PEGAWAI2 WHERE UMUR = 22
-- SELECT * FROM PEGAWAI2 WHERE UMUR < 25
-- SELECT * FROM PEGAWAI2 WHERE UMUR = 22 OR UMUR = 25
-- SELECT * FROM PEGAWAI2 WHERE ID_PEGAWAI IN (1,4,6)
-- SELECT * FROM PEGAWAI2 WHERE NAMA_PEGAWAI LIKE 'AR%'
-- SELECT * FROM PEGAWAI2 WHERE NAMA_PEGAWAI LIKE '%O%'
-- SELECT * FROM PEGAWAI2 WHERE SUBSTR(NAMA_PEGAWAI,2,1) ='A'
-- SELECT COUNT(NAMA_PEGAWAI) FROM PEGAWAI2
-- SELECT MAX(UMUR) FROM PEGAWAI2
-- SELECT UMUR FROM PEGAWAI2 GROUP BY UMUR ORDER BY UMUR ASC
-- SELECT UMUR, COUNT(UMUR) AS JML FROM PEGAWAI2 GROUP BY UMUR

/* 
---------------------------------------------------------------
---------------------------------------------------------------
*/

-- INSERT INTO public.film VALUES ('F001', 'IRON MAN', 'G001', 'A001', 'PD01', 2000000000, 3);
-- INSERT INTO public.film VALUES ('F002', 'IRON MAN 2', 'G001', 'A001', 'PD01', 1800000000, 2);
-- INSERT INTO public.film VALUES ('F003', 'IRON MAN 3', 'G001', 'A001', 'PD01', 1200000000, 0);
-- INSERT INTO public.film VALUES ('F004', 'AVENGER:CIVIL WAR', 'G001', 'A001', 'PD01', 2000000000, 1);
-- INSERT INTO public.film VALUES ('F005', 'SPIDERMAN HOMCOMING', 'G001', 'A001', 'PD01', 1300000000, 0);
-- INSERT INTO public.film VALUES ('F006', 'THE RAID', 'G001', 'A004', 'PD03', 800000000, 5);
-- INSERT INTO public.film VALUES ('F007', 'FAST & FURIOUS', 'G001', 'A004', 'PD05', 830000000, 2);
-- INSERT INTO public.film VALUES ('F008', 'HABIBI DAN AINUN', 'G004', 'A005', 'PD03', 670000000, 4);
-- INSERT INTO public.film VALUES ('F009', 'POLICE STORY', 'G001', 'A003', 'PD02', 700000000, 3);
-- INSERT INTO public.film VALUES ('F010', 'POLICE STORY 2', 'G001', 'A003', 'PD02', 710000000, 1);
-- INSERT INTO public.film VALUES ('F011', 'POLICE STORY 3', 'G001', 'A003', 'PD02', 615000000, 0);
-- INSERT INTO public.film VALUES ('F012', 'RUSH HOUR', 'G003', 'A003', 'PD05', 695000000, 2);
-- INSERT INTO public.film VALUES ('F013', 'KUNGFU PANDA', 'G003', 'A003', 'PD05', 923000000, 5);

-- SELECT * FROM FILM;

/* SOAL 1 */
-- SELECT NM_FILM, NOMINASI FROM FILM ORDER BY NOMINASI DESC
/* SOAL 2 */
-- SELECT NM_FILM, PENDAPATAN FROM FILM ORDER BY PENDAPATAN ASC
/* SOAL 3 */
-- SELECT NM_FILM, NOMINASI FROM FILM WHERE NOMINASI = 0
/* SOAL 4 */
-- SELECT NM_FILM, NOMINASI FROM FILM WHERE NOMINASI = (SELECT MAX(NOMINASI) FROM FILM)
/* SOAL 5 */
-- SELECT NM_FILM, PENDAPATAN FROM FILM WHERE PENDAPATAN = (SELECT MAX(PENDAPATAN) FROM FILM)
/* SOAL 6 */
-- SELECT NM_FILM, PENDAPATAN FROM FILM WHERE PENDAPATAN = (SELECT MIN(PENDAPATAN) FROM FILM)
/* SOAL 7 */
-- SELECT AVG(PENDAPATAN) FROM FILM -- 1095615384.61538462
-- SELECT CEILING(AVG(PENDAPATAN)) FROM FILM -- 1095615385
-- SELECT ROUND(AVG(PENDAPATAN)::NUMERIC,2) FROM FILM -- 1095615384.62
/* SOAL 8 */
-- SELECT AVG(NOMINASI) FROM FILM -- 2.1538461538461538
-- SELECT ROUND(AVG(NOMINASI)::NUMERIC,2) FROM FILM -- 2.15
/* SOAL 9 */
-- SELECT NM_FILM FROM FILM WHERE SUBSTR(UPPER(NM_FILM),1,1) = UPPER('P')
-- SELECT NM_FILM FROM FILM WHERE UPPER(NM_FILM) LIKE UPPER('P%')
-- SELECT NM_FILM FROM FILM WHERE LOWER(NM_FILM) LIKE LOWER('p%')
/* SOAL 10 */
-- SELECT NM_FILM FROM FILM WHERE LOWER(NM_FILM) LIKE LOWER('%h')
/* SOAL 11 */
-- SELECT NM_FILM FROM FILM WHERE LOWER(NM_FILM) LIKE LOWER('%d%')
/* SOAL 12 */
-- SELECT NM_FILM FROM FILM WHERE PENDAPATAN = (SELECT MIN(PENDAPATAN) FROM FILM) AND LOWER(NM_FILM) LIKE LOWER('%o%')
/* SOAL 13 */
-- SELECT NM_FILM FROM FILM WHERE PENDAPATAN = (SELECT MAX(PENDAPATAN) FROM FILM) AND LOWER(NM_FILM) LIKE LOWER('%o%')







